"""initial_schema

Revision ID: 97da68b1d7c5
Revises: 
Create Date: 2026-08-29 03:43:36.408050
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '97da68b1d7c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshots',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('parent_snapshot_id', sa.String(length=100), nullable=True),
    sa.Column('derivation_type', sa.String(length=30), nullable=True),
    sa.Column('derived_from_request_id', sa.String(length=100), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('schema_version', sa.String(length=30), nullable=False),
    sa.Column('raw_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_snapshot_id'], ['snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_hash')
    )
    op.create_table('assets',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('snapshot_id', sa.String(length=100), nullable=False),
    sa.Column('asset_type', sa.String(length=100), nullable=False),
    sa.Column('section_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'snapshot_id')
    )
    op.create_table('conflict_groups',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('snapshot_id', sa.String(length=100), nullable=False),
    sa.Column('conflict_type', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'snapshot_id')
    )
    op.create_table('conflict_group_members',
    sa.Column('conflict_group_id', sa.String(length=100), nullable=False),
    sa.Column('snapshot_id', sa.String(length=100), nullable=False),
    sa.Column('member_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['conflict_group_id', 'snapshot_id'], ['conflict_groups.id', 'conflict_groups.snapshot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conflict_group_id', 'snapshot_id', 'member_id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('snapshot_id', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=30), nullable=False),
    sa.Column('asset_id', sa.String(length=100), nullable=False),
    sa.Column('section_id', sa.String(length=100), nullable=False),
    sa.Column('work_type', sa.String(length=200), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('duration_min_minutes', sa.Integer(), nullable=False),
    sa.Column('duration_max_minutes', sa.Integer(), nullable=False),
    sa.Column('required_resources', sa.JSON(), nullable=False),
    sa.Column('allowed_windows', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'snapshot_id')
    )
    op.create_index('ix_jobs_snapshot', 'jobs', ['snapshot_id'], unique=False)
    op.create_table('planning_runs',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('snapshot_id', sa.String(length=100), nullable=False),
    sa.Column('parent_run_id', sa.String(length=100), nullable=True),
    sa.Column('trigger_type', sa.String(length=30), nullable=False),
    sa.Column('rapidblock_request_id', sa.String(length=100), nullable=True),
    sa.Column('ruleset_version', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('solver_version', sa.String(length=100), nullable=True),
    sa.Column('deterministic_seed', sa.Integer(), nullable=False),
    sa.Column('objective_value', sa.Float(), nullable=True),
    sa.Column('bound', sa.Float(), nullable=True),
    sa.Column('gap', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_run_id'], ['planning_runs.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_planning_runs_snapshot', 'planning_runs', ['snapshot_id'], unique=False)
    op.create_index('ix_planning_runs_state', 'planning_runs', ['state'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('snapshot_id', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('availability', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'snapshot_id')
    )
    op.create_table('sections',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('snapshot_id', sa.String(length=100), nullable=False),
    sa.Column('from_node', sa.String(length=100), nullable=False),
    sa.Column('to_node', sa.String(length=100), nullable=False),
    sa.Column('line', sa.String(length=100), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'snapshot_id')
    )
    op.create_table('train_paths',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('snapshot_id', sa.String(length=100), nullable=False),
    sa.Column('section_id', sa.String(length=100), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'snapshot_id')
    )
    op.create_table('windows',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('snapshot_id', sa.String(length=100), nullable=False),
    sa.Column('section_id', sa.String(length=100), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('availability', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'snapshot_id')
    )
    op.create_index('ix_windows_section_time', 'windows', ['section_id', 'start_at'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('run_id', sa.String(length=100), nullable=False),
    sa.Column('reviewer', sa.String(length=100), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['planning_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('export_records',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('run_id', sa.String(length=100), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['planning_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rapidblock_requests',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('base_run_id', sa.String(length=100), nullable=False),
    sa.Column('base_snapshot_id', sa.String(length=100), nullable=False),
    sa.Column('derived_snapshot_id', sa.String(length=100), nullable=True),
    sa.Column('child_run_id', sa.String(length=100), nullable=True),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('actor_role', sa.String(length=30), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('source_reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('urgent_job_id', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('reason_codes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['base_run_id'], ['planning_runs.id'], ),
    sa.ForeignKeyConstraint(['base_snapshot_id'], ['snapshots.id'], ),
    sa.ForeignKeyConstraint(['child_run_id'], ['planning_runs.id'], ),
    sa.ForeignKeyConstraint(['derived_snapshot_id'], ['snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rapidblock_base_run_state', 'rapidblock_requests', ['base_run_id', 'state'], unique=False)
    op.create_table('schedule_items',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('run_id', sa.String(length=100), nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.Column('window_id', sa.String(length=100), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('reason_codes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['planning_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_schedule_items_run', 'schedule_items', ['run_id'], unique=False)
    op.create_table('validator_results',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('run_id', sa.String(length=100), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['planning_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validator_results')
    op.drop_index('ix_schedule_items_run', table_name='schedule_items')
    op.drop_table('schedule_items')
    op.drop_index('ix_rapidblock_base_run_state', table_name='rapidblock_requests')
    op.drop_table('rapidblock_requests')
    op.drop_table('export_records')
    op.drop_table('approvals')
    op.drop_index('ix_windows_section_time', table_name='windows')
    op.drop_table('windows')
    op.drop_table('train_paths')
    op.drop_table('sections')
    op.drop_table('resources')
    op.drop_index('ix_planning_runs_state', table_name='planning_runs')
    op.drop_index('ix_planning_runs_snapshot', table_name='planning_runs')
    op.drop_table('planning_runs')
    op.drop_index('ix_jobs_snapshot', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('conflict_group_members')
    op.drop_table('conflict_groups')
    op.drop_table('assets')
    op.drop_table('snapshots')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
